[project]
name = "hashlock-lending"
# clarity_version = "4" # This line can be removed

[contracts.hashlock-core]
path = "contracts/hashlock-core.clar"
clarity_version = "4"

[contracts.hashlock-isolated-sbtc-v1]
path = "contracts/hashlock-isolated-sbtc-v1.clar"
clarity_version = "4"

[contracts.safe-vault-base]
path = "contracts/safe-vault-base.clar"
clarity_version = "4"
