[project]
name = "hashlock-lending"
clarity_version = "4"

[contracts.hashlock-core]
path = "contracts/Hashlock-core.clar"
clarity_version = "4"

[contracts.hashlock-isolated-sbtc-v1]
path = "contracts/Hashlock-isolated-sbtc-v1.clar"
clarity_version = "4"

[contracts.safe-vault-base]
path = "contracts/Safe-vault-base.clar"
clarity_version = "4"
