[project]
name = "hashlock-lending"
description = "A trustless lending protocol using sBTC hashlocks."
authors = ["investorphem <dracuul54@gmail.com>"]
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2

[[contracts]]
name = "hashlock-core"
path = "contracts/hashlock-core.clar"
clarity_version = "4"
epoch = "2.1"
depends_on = ["hashlock-isolated-sbtc-v1", "safe-vault-base"]

[[contracts]]
name = "hashlock-isolated-sbtc-v1"
path = "contracts/hashlock-isolated-sbtc-v1.clar"
clarity_version = "4"
epoch = "2.1"

[[contracts]]
name = "safe-vault-base"
path = "contracts/safe-vault-base.clar"
clarity_version = "4"
epoch = "2.1"

[deployment]
network = "mainnet"
account = "deployer"
